import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'PokeNext',
  description: 'Generated by create next app',
  icons:'/images/favicon.ico',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      
      <body className={inter.className}>
        <Navbar/>
        <main className='main-container'>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  )
}
